spring:
  datasource:
   url: jdbc:postgresql://localhost:5432/phone_shops
   username: postgres
   password: Lyhour24
  jpa:
   properties:
    hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    globally_quoted_identifiers: true
   hibernate:
    ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jackson: 
   date-format: yyyy-MM-dd HH:mm:ss
   
